import "katex/dist/katex.min.css"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <div className="container mx-auto p-4">
          <h1 className="text-2xl font-bold text-center">
            Modélisation d'Équations Différentielles
          </h1>
          {children}
        </div>
      </body>
    </html>
  )
}
